formulas:
- name: pipeline
  md5: c7689e6aa9c759f18eeb18ad8706b57b
- name: zh
  md5: 84237988dfc64dbe5571f0b4b08506d0
- name: k8s
  md5: ""
- name: multi-pipeline-zh
  md5: ""
- name: blueocean-zh
  md5: ""
lts:
- 2.204.5
- 2.222.1
- 2.222.3
- 2.222.4
- 2.235.1
- 2.235.2
- 2.235.3
- 2.235.4
- 2.235.5
- 2.249.1
- 2.249.2
weekly:
- "2.223"
- "2.224"
- "2.225"
- "2.226"
- "2.227"
- "2.228"
- "2.229"
- "2.230"
- "2.231"
- "2.232"
- "2.233"
- "2.234"
- "2.235"
- "2.236"
- "2.237"
- "2.238"
- "2.239"
- "2.240"
- "2.241"
- "2.242"
- "2.243"
- "2.244"
- "2.245"
- "2.248"
- "2.249"
- "2.250"
- "2.251"
- "2.252"
- "2.253"
- "2.254"
- "2.255"
- "2.256"
- "2.257"
- "2.258"
- "2.259"
- "2.260"
- "2.261"
- "2.262"
- "2.263"
- "2.264"
