name: Build & Push

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Docker Publish
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER }}
        run: |
          VERSION=$(git tag --list | sort -V | tail -n 1)
          VERSION_BITS=(${VERSION//./ })
          VNUM1=${VERSION_BITS[0]}
          VNUM2=${VERSION_BITS[1]}
          VNUM3=${VERSION_BITS[2]}
          VNUM3=$((VNUM3+1))
          NEW_TAG="$VNUM1.$VNUM2.$VNUM3"
          docker login docker.pkg.github.com --username LinuxSuRen --password ${DOCKER_TOKEN}
          docker build . -t docker.pkg.github.com/jenkins-zh/jenkins-docker/jenkins-zh:$NEW_TAG
          docker push docker.pkg.github.com/jenkins-zh/jenkins-docker/jenkins-zh:$NEW_TAG

          docker login
          docker tag docker.pkg.github.com/jenkins-zh/jenkins-docker/jenkins-zh:$NEW_TAG
          docker push docker.pkg.github.com/jenkins-zh/jenkins-docker/jenkins-zh:$NEW_TAG
      - name: backup
        uses: jenkins-zh/git-backup-actions@v0.0.1
        env:
          GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
          TARGET_GIT: "git@gitee.com:jenkins-zh/mirror-proxy.git"